import { Product } from './types';

export const products: Product[] = [
  // Premium Blends
  {
    id: 'shahi-garam-masala',
    name: 'Shahi Garam Masala',
    category: 'premium-blends',
    description: 'A luxurious blend of premium spices designed for royal dishes. Carefully selected and roasted to perfection, this blend elevates your cooking to restaurant-quality standards.',
    shortDescription: 'Premium royal spice blend',
    price: 299,
    salePrice: 249,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 199, salePrice: 169, stock: 150, sku: 'SGM-100' },
      { id: 'v2', weight: '250g', price: 349, salePrice: 299, stock: 100, sku: 'SGM-250' },
      { id: 'v3', weight: '500g', price: 699, stock: 50, sku: 'SGM-500' },
    ],
    rating: 4.8,
    reviews: 42,
    inStock: true,
    badges: ['lab-tested', 'best-seller'],
    highlights: [
      'No artificial flavors or colors',
      'Lab tested for purity',
      'Region-specific sourcing',
      'Hygienically packed',
    ],
    ingredients: 'Cumin, Coriander, Black Pepper, Cloves, Cinnamon, Bay Leaf, Cardamom',
    storage: 'Store in an airtight container in a cool, dry place. Best consumed within 12 months.',
    usage: 'Add 1-2 teaspoons to curries, rice, soups, and gravies for authentic flavor.',
  },
  {
    id: 'kanda-lasun-chutney',
    name: 'Kanda Lasun Chutney',
    category: 'premium-blends',
    description: 'Traditional onion and garlic chutney powder blend, perfect for pairing with snacks and main courses. Adds instant flavor and aroma to your meals.',
    shortDescription: 'Onion & Garlic chutney blend',
    price: 249,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 149, stock: 120, sku: 'KLC-100' },
      { id: 'v2', weight: '250g', price: 279, stock: 80, sku: 'KLC-250' },
    ],
    rating: 4.6,
    reviews: 28,
    inStock: true,
    badges: ['lab-tested', 'new'],
    highlights: ['Traditional recipe', 'No additives', 'FSSAI certified'],
    ingredients: 'Onions, Garlic, Spices, Salt',
    storage: 'Store in airtight container away from moisture',
    usage: 'Mix with yogurt, add to snacks, or sprinkle over rice',
  },
  {
    id: 'malvani-fish-fry',
    name: 'Malvani Fish Fry Masala',
    category: 'premium-blends',
    description: 'Authentic Malvani coastal spice blend specifically designed for fish and seafood. Brings the flavors of the Konkan coast to your kitchen.',
    shortDescription: 'Coastal fish masala blend',
    price: 269,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 169, stock: 100, sku: 'MFF-100' },
      { id: 'v2', weight: '250g', price: 299, stock: 60, sku: 'MFF-250' },
    ],
    rating: 4.7,
    reviews: 35,
    inStock: true,
    badges: ['lab-tested', 'best-seller'],
    highlights: ['Coastal authentic blend', 'Perfect for seafood', 'Traditional recipe'],
    ingredients: 'Red Chilli, Cumin, Coriander, Turmeric, Coconut, Fenugreek',
    storage: 'Keep in cool, dry place',
    usage: 'Perfect for marinating and frying fish, prawns, or squid',
  },
  {
    id: 'kala-masala',
    name: 'Kala Masala',
    category: 'premium-blends',
    description: 'Premium dark spice blend with a rich, complex flavor profile. Perfect for biryanis, meat curries, and special dishes.',
    shortDescription: 'Premium dark spice blend',
    price: 329,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 199, stock: 80, sku: 'KM-100' },
      { id: 'v2', weight: '250g', price: 349, stock: 50, sku: 'KM-250' },
    ],
    rating: 4.5,
    reviews: 22,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['Complex flavor', 'Premium blend', 'For special occasions'],
    ingredients: 'Black Cumin, Black Cardamom, Star Anise, Bay Leaf, Cloves',
    storage: 'Store in sealed container',
    usage: 'Add to biryani, pulao, and meat curries',
  },
  {
    id: 'goda-masala',
    name: 'Goda Masala',
    category: 'premium-blends',
    description: 'Authentic Maharashtrian sweet spice blend. Essential for authentic misal and other traditional dishes. A perfect blend of sweet and savory notes.',
    shortDescription: 'Maharashtrian sweet masala',
    price: 249,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 159, stock: 110, sku: 'GM-100' },
      { id: 'v2', weight: '250g', price: 299, stock: 70, sku: 'GM-250' },
    ],
    rating: 4.9,
    reviews: 58,
    inStock: true,
    badges: ['best-seller', 'lab-tested'],
    highlights: ['Authentic Maharashtrian recipe', 'Sweet & savory', 'FSSAI certified'],
    ingredients: 'Cumin, Coriander, Jaggery, Coconut, Gram Dal, Peanuts',
    storage: 'Store in airtight container',
    usage: 'Essential for misal pav, khandvi, and traditional dishes',
  },
  {
    id: 'mutton-masala',
    name: 'Mutton Masala',
    category: 'premium-blends',
    description: 'Specially crafted spice blend for mutton and lamb dishes. Enhances the rich flavors and creates authentic, aromatic meat curries.',
    shortDescription: 'Mutton spice blend',
    price: 349,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 219, stock: 90, sku: 'MM-100' },
      { id: 'v2', weight: '250g', price: 399, stock: 50, sku: 'MM-250' },
    ],
    rating: 4.6,
    reviews: 31,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['Perfect for mutton', 'Rich flavors', 'Authentic recipe'],
    ingredients: 'Red Chilli, Cumin, Coriander, Fenugreek, Black Pepper, Ginger',
    storage: 'Keep in sealed container away from heat',
    usage: 'Perfect for mutton biryani, curry, and kebabs',
  },
  {
    id: 'chicken-masala',
    name: 'Chicken Masala',
    category: 'premium-blends',
    description: 'Aromatic spice blend designed specifically for chicken dishes. Creates tender, flavorful curries and tandoori preparations.',
    shortDescription: 'Chicken spice blend',
    price: 279,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 179, stock: 120, sku: 'CM-100' },
      { id: 'v2', weight: '250g', price: 319, stock: 80, sku: 'CM-250' },
    ],
    rating: 4.7,
    reviews: 44,
    inStock: true,
    badges: ['best-seller', 'lab-tested'],
    highlights: ['Perfect for chicken', 'Tender & flavorful', 'Widely loved'],
    ingredients: 'Cumin, Coriander, Turmeric, Red Chilli, Ginger, Garlic',
    storage: 'Store in cool, dry place',
    usage: 'Great for curry, tandoori, and fried chicken',
  },
  {
    id: 'shahi-biryani-masala',
    name: 'Shahi Biryani Masala',
    category: 'premium-blends',
    description: 'Premium spice blend crafted for authentic biryani preparation. Brings restaurant-quality taste to your home kitchen.',
    shortDescription: 'Royal biryani spice blend',
    price: 399,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 249, stock: 70, sku: 'SBM-100' },
      { id: 'v2', weight: '250g', price: 449, stock: 40, sku: 'SBM-250' },
    ],
    rating: 4.8,
    reviews: 67,
    inStock: true,
    badges: ['best-seller', 'lab-tested'],
    highlights: ['Royal blend', 'Restaurant quality', 'Aromatic spices'],
    ingredients: 'Black Cardamom, Cinnamon, Cloves, Star Anise, Mace, Bay Leaf',
    storage: 'Keep sealed away from sunlight',
    usage: 'Add to biryani rice and meat for authentic flavor',
  },
  {
    id: 'kolhapuri-misal-masala',
    name: 'Kolhapuri Misal Masala',
    category: 'premium-blends',
    description: 'Authentic fiery spice blend from Kolhapur. Perfect for misal pav and other spicy Maharashtrian preparations.',
    shortDescription: 'Spicy misal blend',
    price: 229,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 149, stock: 130, sku: 'KMM-100' },
      { id: 'v2', weight: '250g', price: 269, stock: 90, sku: 'KMM-250' },
    ],
    rating: 4.5,
    reviews: 38,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['Fiery & authentic', 'Kolhapuri recipe', 'Perfect for misal'],
    ingredients: 'Red Chilli, Coriander, Cumin, Turmeric, Asafoetida',
    storage: 'Store in sealed container',
    usage: 'Mix into misal pav curry for authentic Kolhapuri taste',
  },
  {
    id: 'kolhapuri-lal-tikhat',
    name: 'Kolhapuri Lal Tikhat Masala',
    category: 'premium-blends',
    description: 'Traditional red hot spice blend from Kolhapur region. Known for its fiery heat and authentic taste.',
    shortDescription: 'Red hot Kolhapuri blend',
    price: 239,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 159, stock: 110, sku: 'KLT-100' },
      { id: 'v2', weight: '250g', price: 289, stock: 70, sku: 'KLT-250' },
    ],
    rating: 4.6,
    reviews: 42,
    inStock: true,
    badges: ['lab-tested', 'best-seller'],
    highlights: ['Fiery heat', 'Authentic Kolhapuri', 'Traditional blend'],
    ingredients: 'Red Chilli, Fenugreek, Coriander, Cumin, Asafoetida',
    storage: 'Keep in sealed container away from moisture',
    usage: 'Perfect for spicy gravies and traditional dishes',
  },

  // Core Range
  {
    id: 'turmeric-powder',
    name: 'Turmeric Powder',
    category: 'core-range',
    description: 'Pure, lab-tested turmeric powder with no additives. Golden yellow color and natural warming properties. Essential for every kitchen.',
    shortDescription: 'Pure turmeric powder',
    price: 149,
    salePrice: 129,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 99, stock: 200, sku: 'TUR-100' },
      { id: 'v2', weight: '250g', price: 179, stock: 150, sku: 'TUR-250' },
      { id: 'v3', weight: '500g', price: 349, stock: 100, sku: 'TUR-500' },
    ],
    rating: 4.9,
    reviews: 125,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['100% pure', 'No additives', 'Lab tested', 'Rich color'],
    ingredients: 'Pure Turmeric',
    storage: 'Keep dry, away from moisture and direct sunlight',
    usage: 'Add to curries, rice, soups, and drinks. 1 teaspoon per serving.',
  },
  {
    id: 'red-chilli-powder',
    name: 'Red Chilli Powder',
    category: 'core-range',
    description: 'Pure red chilli powder made from finest chilies. Adds vibrant color and spicy kick to any dish. Lab tested for quality.',
    shortDescription: 'Pure red chilli powder',
    price: 179,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 129, stock: 180, sku: 'RCP-100' },
      { id: 'v2', weight: '250g', price: 229, stock: 120, sku: 'RCP-250' },
      { id: 'v3', weight: '500g', price: 429, stock: 80, sku: 'RCP-500' },
    ],
    rating: 4.8,
    reviews: 98,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['Pure chilli', 'No filler', 'Vibrant color', 'Spicy kick'],
    ingredients: 'Pure Red Chilli',
    storage: 'Store in airtight container away from sunlight',
    usage: 'Add to curries, snacks, and vegetables for color and spice',
  },
  {
    id: 'coriander-powder',
    name: 'Coriander Powder',
    category: 'core-range',
    description: 'Ground coriander seeds with aromatic flavor. Perfect for everyday cooking and special recipes.',
    shortDescription: 'Coriander powder',
    price: 169,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 119, stock: 160, sku: 'COR-100' },
      { id: 'v2', weight: '250g', price: 209, stock: 110, sku: 'COR-250' },
      { id: 'v3', weight: '500g', price: 389, stock: 70, sku: 'COR-500' },
    ],
    rating: 4.7,
    reviews: 76,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['Aromatic', 'Pure blend', 'Freshly ground'],
    ingredients: 'Pure Coriander Seeds',
    storage: 'Keep sealed in cool place',
    usage: 'Essential spice for Indian cooking, add to curries and rice',
  },
  {
    id: 'cumin-powder',
    name: 'Cumin Powder',
    category: 'core-range',
    description: 'Pure roasted cumin powder with earthy, warm flavor. Essential ingredient for authentic Indian cooking.',
    shortDescription: 'Cumin powder',
    price: 179,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 129, stock: 170, sku: 'CUM-100' },
      { id: 'v2', weight: '250g', price: 229, stock: 115, sku: 'CUM-250' },
      { id: 'v3', weight: '500g', price: 419, stock: 75, sku: 'CUM-500' },
    ],
    rating: 4.8,
    reviews: 89,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['Warm flavor', 'Freshly roasted', 'Pure & pure'],
    ingredients: 'Pure Cumin Seeds',
    storage: 'Store in airtight container away from heat',
    usage: 'Add to vegetable curries, tempered oils, and slow-cooked dishes',
  },
  {
    id: 'chaat-masala',
    name: 'Chaat Masala',
    category: 'core-range',
    description: 'Tangy and flavorful chaat masala blend. Perfect for street food, snacks, and chaat items. Adds instant zing to any dish.',
    shortDescription: 'Chaat masala blend',
    price: 189,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&h=800&fit=crop',
    ],
    variants: [
      { id: 'v1', weight: '100g', price: 139, stock: 150, sku: 'CHA-100' },
      { id: 'v2', weight: '250g', price: 249, stock: 100, sku: 'CHA-250' },
      { id: 'v3', weight: '500g', price: 459, stock: 60, sku: 'CHA-500' },
    ],
    rating: 4.6,
    reviews: 64,
    inStock: true,
    badges: ['lab-tested'],
    highlights: ['Tangy flavor', 'Street food special', 'Versatile use'],
    ingredients: 'Cumin, Coriander, Amchur, Chilli, Salt, Asafoetida',
    storage: 'Keep in sealed container',
    usage: 'Sprinkle on chaats, fruits, snacks, and salads',
  },
];

export const getProductById = (id: string) => {
  return products.find((p) => p.id === id);
};

export const getProductsByCategory = (category: string) => {
  return products.filter((p) => p.category === category);
};

export const searchProducts = (query: string) => {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.includes(q)
  );
};
